# Generated by Django 4.0.2 on 2022-05-07 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('study', 'Study'), ('helpSession', 'HelpSession'), ('sport', 'Sport'), ('game', 'Game'), ('other', 'Other')], max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location_url', models.URLField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('cancelled', 'Cancelled'), ('finished', 'Finished')], max_length=30)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='campus.campus')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_events', to='campus.residentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.URLField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='event.event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('joined', 'Joined'), ('cancelled', 'Cancelled')], max_length=30)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='event.event')),
                ('resident_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_applications', to='campus.residentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
