# Generated by Django 4.0.2 on 2022-03-08 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0002_alter_building_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('joined', 'Joined'), ('cancelled', 'Cancelled')], max_length=30)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_events', to='campus.residentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('study', 'Study'), ('Help Session', 'HelpSession'), ('sport', 'Sport'), ('game', 'Game'), ('other', 'Other')], max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location_url', models.URLField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('new', 'New'), ('cancelled', 'Cancelled'), ('finished', 'Finished')], max_length=30)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_events', to='campus.residentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
