# Generated by Django 4.0.4 on 2022-05-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.URLField(max_length=1024),
        ),
    ]
