# Generated by Django 4.0.2 on 2022-04-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_rename_resident_eventapplication_resident_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('cancelled', 'Cancelled'), ('finished', 'Finished')], max_length=30),
        ),
    ]
