# Generated by Django 4.0.2 on 2022-04-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('study', 'Study'), ('helpSession', 'HelpSession'), ('sport', 'Sport'), ('game', 'Game'), ('other', 'Other')], max_length=30),
        ),
    ]
