# Generated by Django 4.0.2 on 2022-03-07 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('campus', 'Campus'), ('building', 'Building'), ('advertisement', 'Advertisement')], max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommercialAnnouncement',
            fields=[
                ('announcement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='announcement.announcement')),
                ('impressions', models.IntegerField(default=0)),
                ('advertiser_name', models.CharField(max_length=50)),
                ('link', models.URLField(blank=True, null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.campus')),
            ],
            options={
                'abstract': False,
            },
            bases=('announcement.announcement',),
        ),
        migrations.CreateModel(
            name='CampusAnnouncement',
            fields=[
                ('announcement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='announcement.announcement')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.campus')),
            ],
            options={
                'abstract': False,
            },
            bases=('announcement.announcement',),
        ),
        migrations.CreateModel(
            name='BuildingAnnouncement',
            fields=[
                ('announcement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='announcement.announcement')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.building')),
            ],
            options={
                'abstract': False,
            },
            bases=('announcement.announcement',),
        ),
    ]
