# Generated by Django 4.0.4 on 2022-05-08 10:44

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialannouncement',
            name='image',
            field=models.FileField(blank=True, max_length=2048, null=True, upload_to=core.utils.PathAndRename('uploads/commercials/images/2022/05/08')),
        ),
        migrations.AlterField(
            model_name='commercialannouncement',
            name='link',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
