# Generated by Django 4.0.2 on 2022-03-08 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingannouncement',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='campus.building'),
        ),
        migrations.AlterField(
            model_name='campusannouncement',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='campus.campus'),
        ),
        migrations.AlterField(
            model_name='commercialannouncement',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_announcements', to='campus.campus'),
        ),
    ]
