# Generated by Django 4.0.2 on 2022-04-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='image',
            field=models.URLField(),
            preserve_default=False,
        ),
    ]
