# Generated by Django 4.0.2 on 2022-04-26 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0011_alter_campus_image'),
        ('post', '0002_postimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='beneficiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_applications', to='campus.residentprofile'),
        ),
    ]
