# Generated by Django 4.0.2 on 2022-05-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceissue',
            name='type',
            field=models.CharField(choices=[('halls', 'Halls'), ('rooms', 'Rooms'), ('bathrooms', 'Bathrooms'), ('other', 'Other')], max_length=30),
        ),
    ]
