# Generated by Django 4.0.2 on 2022-04-23 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0004_maintenanceissue_reported_fixed'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceissue',
            name='reported_fixed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_fixed_issues', to='campus.residentprofile'),
        ),
    ]
