# Generated by Django 4.0.2 on 2022-04-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0005_maintenanceissue_reported_fixed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenanceissue',
            name='reported_fixed_by',
        ),
        migrations.AddField(
            model_name='maintenanceissue',
            name='reported_fixed_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='reported_fixed_issues', to='campus.ResidentProfile'),
        ),
    ]
