# Generated by Django 4.0.2 on 2022-04-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0006_remove_maintenanceissue_reported_fixed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceissue',
            name='reported_fixed_by',
            field=models.ManyToManyField(related_name='reported_fixed_issues', to='campus.ResidentProfile'),
        ),
    ]
