# Generated by Django 4.0.2 on 2022-04-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0007_alter_maintenanceissue_reported_fixed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceissue',
            name='type',
            field=models.CharField(choices=[('halls', 'Halls'), ('rooms', 'Rooms'), ('bathroom', 'Bathrooms'), ('other', 'Other')], max_length=30),
        ),
    ]
