# Generated by Django 4.0.2 on 2022-04-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0009_building_location_url_campus_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentprofile',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
