# Generated by Django 4.0.2 on 2022-05-06 06:54

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0014_alter_maintenanceissue_reported_fixed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentprofile',
            name='num_of_raters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='rating',
            field=models.FloatField(default=0),
        )
    ]
