# Generated by Django 4.0.2 on 2022-04-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('SMS', 'SMS'), ('Email', 'Email'), ('PushNotification', 'PushNotification')], max_length=50),
        ),
    ]
