# Generated by Django 4.0.2 on 2022-03-12 00:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Username is a student id. (e.g. s201477960 or t201022347)', regex='^(([A-z][0-9]+)|([0-9]+))$')])),
                ('is_active', models.BooleanField(default=True)),
                ('otp', models.CharField(max_length=4)),
                ('expiration_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
